### ISSUE TITLE
IE10 uploading twice, or not at all.

### ISSUE THREAD

**Issue by MattWatt** [danialfarid/angular-file-upload#451]
Nice library, however I'm encountering some strangeness with IE10.  

If I choose the same file after an attempt at uploading, my file model is a blank string.  A 3rd attempt and it's an empty array, according to VS.

If I choose a file and it's successfully uploaded, the next time I attempt to a file, it fires my ng-file-change function twice with the same file.

I've looked over the other issues:
https://github.com/danialfarid/angular-file-upload/issues/235
https://github.com/danialfarid/angular-file-upload/issues/141#issuecomment-35763069

It appears this was supposed to be corrected recently.

I'm running 2.0.4.  Attempting to do a single file at a time upload behavior.  Hoping you can take a look.  I'm running native IE10 in Standards mode.  Behavior works correctly in Chrome.

My HTML
```html
<button type="button" class="button-primary" ng-file-select ng-model="file" ng-file-change="addAttachment(file)" ng-multiple="false">
    Add Attachment
</button>
```

My Controller's JS Function:
```javascript
$scope.addAttachment = function addAttachment(file) {

    // Validate File Size
    var maxFileSizeBytes = 10000000;  // 10 MB
    if (file[0].size > maxFileSizeBytes) {
        //alert("The file must not exceed 10 MB");
        console.log("The file exceeded the max size");
        return;
    }

    var data = {
        stepUid: $scope.step.StepUID,
        userName: trContextSvc.getContext().name
    };

    // Upload the file using the Angular File Uploader
    $upload.upload({
        url: '/Project/' + $scope.ProjectID + '/Step/AddAttachment',
        method: 'POST',
        data: data,
        file: file
    }).progress(function (evt) {
        console.log('progress: ' + parseInt(100.0 * evt.loaded / evt.total) + '% file :' + evt.config.file[0].name);
    }).then(function (response) {
        $timeout(function () {
            // file is uploaded successfully
            console.log('file ' + response.config.file[0].name + 'is uploaded successfully.');
            $scope.step.Attachments.push(response.data);
        });
    });
};
```

Like I said, on a second upload attempt, after a successful one, the AddAttachment(file) function is fired twice with the same file.  Only in IE10, so far.

If I choose a file that fails my max size limit, on subsequent button click, the dialog options, noticing the previous filename is already in the box.  Choosing it again results in file = "" and then file = [], and this alternates on button presses.

Thanks for your help.

**Comment by danialfarid** [comment]
This should be fixed in version 2.1.1.

**Comment by gamebox** [comment]
Just as clarification, this is only fixed if you do not have a $watch set on files correct?

**Comment by danialfarid** [comment]
no it should work as expected whether you have watch or function.

**Comment by gamebox** [comment]
Interesting, I am still having this issue reported to me by users of IE 10 on Windows 8.  I don't have access to a windows machine at home or at the office, so I'm at a little bit of a loss for debugging the issue.

**Comment by SlippySken** [comment]
it seems like i have the same problem on 2.1.1

**Comment by akshay-bbytes** [comment]
`onclick="this.value = null"` worked fine for me thanks

**Comment by sunnyrainywen** [comment]
I met the question too, does this issue been fixed now?
